server:
  port: 8999
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path= /user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/user-service-fallback
        -  id: contact-service
           uri: lb://contact-service
           predicates:
             - Path= /contact/**
           filters:
             - name: CircuitBreaker
               args:
                 name: contact-service
                 fallbackuri: forward:/contact-service-fallback
eureka:
  instance:
    hostname: localhost

hystrix:
  commands:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMillieSecond: 5000

management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream
